// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erwstanhwmsbgqilorpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyd3N0YW5od21zYmdxaWxvcnB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTA0NTAsImV4cCI6MjA5MDYyNjQ1MH0.Z7w-Y7ZghUSiVcWVlkrfLbjRy4WQsqES3oGCuQnCYsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    detectSessionInUrl: true,
    persistSession: true,
    autoRefreshToken: true,
  }
});